name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Waifuclient.sln
      NVM_DIR: $HOME/.nvm
      #Test_Project_Path: your-test-project-path

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      run: |
          sudo apt update -y
          sudo apt install -y wget
          wget -qO- https://deb.nodesource.com/setup_20.x | sudo bash
          sudo apt update -y
          sudo apt install -y nodejs

    - name: Setup zip
      run: |
        sudo apt update -y
        sudo apt install -y zip

    - name: Update changelog
      if: startsWith(github.ref, 'refs/tags/')
      run: npm exec -c 'git-cliff --current --output CHANGELOG.md'
    
    #- name: Execute unit tests
    #  run: dotnet test

    - name: Build
      run: |
        dotnet publish -c Release -r win-x64 --self-contained
        dotnet publish -c Release -r linux-x64 --self-contained
        
    - name: Pack release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd Waifuclient/bin/Release/net8.0/win-x64/publish
        zip -r Waifuclient-Win-x64.zip *
        cd ../../
        cd linux-x64/publish
        zip -r Waifuclient-Linux-x64.zip *
        cd ../../../../../
      
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.MD
        files: |
          Waifuclient/bin/Release/net6.0/win-x86/publish/ReForm-Win-x64.zip
          Waifuclient/bin/Release/net6.0/win-x86/publish/ReForm-Linux-x64.zip

