name: .NET Core Desktop

on:
  push:
    branches:
      - 'master'

jobs:

  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    permissions:
      contents: write

    env:
      Solution_Name: Waifuclient.sln
      NVM_DIR: $HOME/.nvm
      #Test_Project_Path: your-test-project-path

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      run: |
          sudo apt update -y
          sudo apt install -y wget
          wget -qO- https://deb.nodesource.com/setup_20.x | sudo bash
          sudo apt update -y
          sudo apt install -y nodejs

    - name: Setup zip
      run: |
        sudo apt update -y
        sudo apt install -y zip

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        useConfigFile: true

    - name: Push Git Tag
      run: | 
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git tag ${{ env.GitVersion_MajorMinorPatch }} -m ${{ env.GitVersion_MajorMinorPatch }}
        git add *
        git commit -m "v${{ env.GitVersion_MajorMinorPatch }}"
        git push origin ${{ env.GitVersion_MajorMinorPatch }}

    - name: Update changelog
      run: |
          npm update
          npm exec -c 'git-cliff --current --output ${{ github.workspace }}/CHANGELOG.md'

    #- name: Execute unit tests
    #  run: dotnet test

    - name: Build
      run: |
        dotnet publish -c Release -r win-x64 --self-contained
        dotnet publish -c Release -r linux-x64 --self-contained
        
    - name: Pack release
      run: |
        dotnet-gitversion -config GitVersion.yml -updateprojectfiles
        cd Waifuclient/bin/Release/net8.0/win-x64/publish
        zip -r ${{ github.workspace }}/WaifuClient-Win-x64.zip *
        cd ../../
        cd linux-x64/publish
        zip -r ${{ github.workspace }}/Waifuclient-Linux-x64.zip *
      
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.GitVersion_MajorMinorPatch }}
        name: ${{ env.GitVersion_FullSemVer }}
        artifacts: "*.zip"
        bodyFile: "CHANGELOG.md"

